version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - run:
          name: Install Deps
          command: npm install
      - run:
          name: Build the extension
          command: npm run compile
